name: Azure Deployment

on:
  push:
    branches:
      - azure

env:
  NODE_VERSION: '10.x'
  STORAGE_ACCOUNT: 'mrakopresentation'
  SUBSCRIPTION_ID: 'cb993fcd-e915-40be-ba4d-11c39b991a0c'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: npm ci
    - run: npm run build

    - name: Deploy to Azure bucket
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob upload-batch -s public -d '$web' --account-name ${{ env.STORAGE_ACCOUNT }} --subscription ${{ env.SUBSCRIPTION_ID }}
